# -*- coding: utf-8 -*-

"""
  runfast version 1.0

  Django settings for recharge project.

  Generated by 'django-admin startproject' using Django 1.9.

  For more information on this file, see
  https://docs.djangoproject.com/en/1.9/topics/settings/

  For the full list of settings and their values, see
  https://docs.djangoproject.com/en/1.9/ref/settings/
"""

# pylint: disable = protected-access, invalid-name

from recharge.settings import *

STATIC_URL = 'https:' + STATIC_URL

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'yuan.contrib.crashlog.middleware.CrashLogMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'yuan.middleware.StripWhitespaceMiddleware',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(D_APP_ROOT, 'templates'),
            os.path.join(D_APP_ROOT, 'vendor/apps/yuan/contrib/console/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
                'yuan.http.context_processors.siteinfo',
            ],
        },
    },
]

ROOT_URLCONF = 'backbone.urls'

WSGI_APPLICATION = 'backbone.wsgi.application'