# -*- coding: utf-8 -*-

"""
  recharge version 1.0

  Django settings for recharge project.

  Generated by 'django-admin startproject' using Django 1.10.3

  For more information on this file, see
  https://docs.djangoproject.com/en/1.9/topics/settings/

  For the full list of settings and their values, see
  https://docs.djangoproject.com/en/1.9/ref/settings/
"""

from recharge.settings import *

STATIC_URL = 'https:' + STATIC_URL

ROOT_URLCONF = 'console.urls'

WSGI_APPLICATION = 'console.wsgi.application'